// wordData.js
const wordList = {
    "punting": "They spent the afternoon punting down the quiet river.",
    "crowd": "The crowd cheered loudly at the concert.",
    "secret": "She told her best friend a big secret.",
    "fumble": "He made a fumble during the football game.",
    "pond": "The ducks swam peacefully across the pond.",
    "health": "Eating vegetables is good for your health.",
    "pardon": "Pardon me, I didn’t mean to bump into you.",
    "shake": "Give the bottle a good shake before drinking.",
    "kiddo": "Time for bed, kiddo!",
    "proof": "She needed proof that the story was true.",
    "gorp": "We snacked on gorp during our hike.",
    "town": "They visited a small mountain town.",
    "bingo": "Grandma won the game of bingo!",
    "clever": "The clever fox escaped the trap.",
    "inside": "It’s cold outside, let’s stay inside.",
    "reply": "Please reply to the invitation.",
    "frozen": "The lake was completely frozen over.",
    "special": "This necklace is very special to me.",
    "film": "We watched a funny film last night.",
    "results": "The test results came back positive.",
    "soda": "He opened a can of soda.",
    "seal": "The seal balanced a ball on its nose.",
    "twirled": "She twirled in her new dress.",
    "admit": "You must admit when you're wrong.",
    "grown-ups": "The grown-ups sat at a separate table.",
    "pieces": "The puzzle was missing two pieces.",
    "brass": "The trumpet is made of brass.",
    "onshore": "The boat drifted back onshore.",
    "stunts": "The movie was full of amazing stunts.",
    "deny": "Don't deny what really happened.",
    "jolly": "Santa Claus is a jolly old man.",
    "powder": "The snow turned to soft powder.",
    "walnut": "She cracked open the walnut.",
    "sawdust": "The floor was covered in sawdust.",
    "flustered": "She looked flustered before the test.",
    "barber": "The barber gave me a great haircut.",
    "chimes": "The wind chimes rang softly.",
    "cabin": "They stayed in a cozy cabin in the woods.",
    "faint": "The sound was too faint to hear clearly.",
    "manger": "Baby Jesus was laid in a manger.",
    "peppermint": "I love the taste of peppermint.",
    "broth": "The chicken broth smelled delicious.",
    "ash": "The campfire burned down to ash.",
    "flame": "The candle flame flickered.",
    "grits": "He ate grits for breakfast.",
    "cliff": "They stood at the edge of the cliff.",
    "hem": "She sewed the hem of the skirt.",
    "candles": "We lit candles for the birthday cake.",
    "brim": "His hat had a wide brim.",
    "plot": "The book had a surprising plot twist.",
    "desk": "Her desk was covered in papers.",
    "bopcat": "The bopcat danced to the funky beat.", // fun made-up word
    "polo": "They played a game of water polo.",
    "roller": "He used a roller to paint the wall.",
    "stark": "The desert was a stark landscape.",
    "drum": "The drummer beat on the big drum.",
    "snarl": "The dog gave a low snarl.",
    "argue": "They began to argue over the game.",
    "loppers": "Use loppers to trim the tree branches.",
    "petal": "A single petal fell from the rose.",
    "giant": "A giant stood at the top of the hill.",
    "sniffle": "She had a small sniffle from the cold.",
    "mouth": "He opened his mouth to yawn.",
    "filters": "The water filters need replacing.",
    "cone": "He dropped his ice cream cone.",
    "never": "I will never forget this day.",
    "silly": "That’s such a silly joke!",
    "Monday": "Monday is the first day of the school week.",
    "grub": "Let’s get some grub after the hike.",
    "hook": "Hang your coat on the hook.",
    "number": "Please pick a number between one and ten.",
    "cooking": "She enjoys cooking with her grandma.",
    "amazed": "They were amazed by the fireworks.",
    "collect": "He likes to collect baseball cards.",
    "local": "We bought apples from the local market.",
    "proper": "Use the proper tools for the job.",
    "basement": "The basement was dark and quiet.",
    "ripple": "A ripple spread across the pond.",
    "feats": "The gymnast performed amazing feats.",
    "plumbing": "The house had old plumbing.",
    "stubborn": "The mule was very stubborn.",
    "adrift": "The raft was adrift in the ocean.",
    "sweeten": "Add sugar to sweeten the lemonade.",
    "neon": "The neon sign glowed brightly.",
    "beeswax": "He used beeswax to polish the wood.",
    "social": "Social skills are important.",
    "behold": "Behold the beauty of the sunrise.",
    "mix": "Mix the batter until smooth.",
    "drool": "The baby began to drool.",
    "understand": "I finally understand the problem.",
    "sound": "What’s that sound in the attic?",
    "benches": "The park had many benches.",
    "shrugged": "She shrugged and walked away.",
    "still": "Sit still during the movie.",
    "pranks": "April Fools' Day is full of pranks.",
    "smiled": "She smiled at the compliment.",
    "peach": "I picked a ripe peach from the tree.",
    "pie": "Apple pie is my favorite dessert.",
    "size": "What size shoes do you wear?",
    "hall": "The hall was decorated with balloons.",
    "jangled": "His keys jangled in his pocket.",
    "chain": "The swing hung from a metal chain.",
    "workhorse": "This old truck is a real workhorse.",
    "antennas": "The antennas picked up a weak signal.",
    "honest": "Always try to be honest.",
    "holler": "He let out a loud holler.",
    "billboard": "The billboard showed a new movie.",
    "chicken": "We had chicken for dinner.",
    "puppets": "The children put on a puppet show.",
    "waited": "She waited patiently in line.",
    "finish": "Finish your homework before playing.",
    "cheer": "The crowd let out a big cheer.",
    "twisty": "The road was long and twisty.",
    "chips": "He ate chips with salsa.",
    "scoop": "Give me one scoop of vanilla, please.",
    "rover": "Rover is our family dog.",
    "forgive": "It’s important to forgive others.",
    "ribbon": "She tied the ribbon in her hair.",
    "shoo": "Shoo the flies away!",
    "greedy": "The greedy boy grabbed all the toys.",
    "beam": "A beam of light shone through the window.",
    "crew": "The crew prepared the ship for sailing.",
    "crate": "They moved the crate into storage.",
    "hotel": "We stayed in a fancy hotel.",
    "stray": "A stray cat showed up at the door."
  };
  